<?php


function gai_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	if($form_id === 'contact_message_feedback_form') {
		$form['actions']['submit']['#submit'][]  = 'custom_node_form_submit';	


	}
	if($form_id === 'contact_message_request_for_a_quote_form') {
		$form['actions']['submit']['#submit'][]  = 'custom_node_form_submit';	


	}
	
}

function custom_node_form_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
	unset($_SESSION['messages']['status']);
	drupal_set_message(t('Thank you for contacting Us! We will get back to you shortly.'));
}

